version: "3.7"

services:
  web:
    depends_on:
      - postgres
    restart: "unless-stopped"
    container_name: "web"
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
  postgres:
    restart: unless-stopped
    container_name: "db"
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
      
volumes:
  postgres_data:
