"""migration_name

Revision ID: c33b272573f4
Revises: c5895fc1f40f
Create Date: 2023-06-14 04:00:38.243752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33b272573f4'
down_revision = 'c5895fc1f40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
