"""migration_name

Revision ID: b4fcd83738a8
Revises: 7ed507c7550e
Create Date: 2023-06-14 04:04:19.888581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4fcd83738a8'
down_revision = '7ed507c7550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
